name: Pull Request Checks

permissions:
  contents: read
  pull-requests: write
  checks: write

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check PR description
        id: pr-check
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            const body = pullRequest.body;
            
            // Check if the checkboxes are ticked
            const apiChangesChecked = body.includes('- [x] Did any changes in API?');
            const screenshotChecked = body.includes('- [x] Have you attached screenshots?');
            
            // Check for the presence of screenshots (assuming they are linked or embedded)
            const hasScreenshots = body.includes('![') || body.includes('http');
            
            let failureReason = '';
            
            if (screenshotChecked && !hasScreenshots) {
              failureReason = 'Screenshots are marked as attached, but none were found in the PR description.';
            } else if (apiChangesChecked && !screenshotChecked) {
              failureReason = 'API changes are marked, but screenshots are not attached. Screenshots are mandatory for API changes.';
            } else if (apiChangesChecked && screenshotChecked && !hasScreenshots) {
              failureReason = 'API changes and screenshots are marked, but no screenshots were found in the PR description.';
            }
            
            if (failureReason) {
              core.setFailed(failureReason);
            } else {
              console.log('All checks passed successfully!');
            }

      - name: PR Check Result
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const checkConclusion = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            const checkOutput = checkConclusion === 'success' 
              ? { title: 'PR Checks Passed', summary: 'All PR checks have passed successfully.' }
              : { title: 'PR Checks Failed', summary: '${{ steps.pr-check.outputs.error-message || 'PR checks have failed. Please review the workflow for more details.' }}' };
            
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'PR Checks',
              head_sha: context.sha,
              status: 'completed',
              conclusion: checkConclusion,
              output: checkOutput
            });
            
            if (checkConclusion === 'failure') {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'PR checks failed. Please address the following issues before merging:\n\n' + 
                      '${{ steps.pr-check.outputs.error-message || 'Check the workflow logs for more details.' }}'
              });
            }
