name: 'PR Check'

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check for Screenshots in PR Description'
        id: screenshot-check
        run: |
          echo "PR Description: ${{ github.event.pull_request.body }}"
          if [[ "${{ github.event.pull_request.body }}" != *"![Screenshot]"* ]]; then
            echo "No screenshots found in the PR description."
            exit 1
          fi
        shell: bash

      - name: 'Fail if screenshot check fails'
        if: failure()
        run: |
          echo "PR does not meet the requirements. Please add screenshots to the PR description."
          exit 1
